name: yeast-oxidative-stress-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - nextflow=23.10.1
  - fastqc=0.11.9
  - fastp=0.23.4
  - hisat2=2.2.1
  - samtools=1.17
  - subread=2.0.6
  - r-base=4.3.2
  - r-essentials
  - bioconductor-edger
  - r-ggplot2
  - r-dplyr
  - r-ggrepel
  - r-pheatmap
  - r-rcolorbrewer
  - r-data.table
  - gffread
  - sra-tools
  - pigz
